global_batch_size: &global_batch_size 48
device: &device cpu
# device: &device 'cuda:0'
max_epoch: 10
weight_decay: &weight_decay 0.00001

dynamic_parsing_part:
  input_data: &input_data
    parser_element: ['train_loader', 'eval_loader']
    parser_rule:
      define_file_path: module_lib.data_loader.data_loader_mnist
      run_key: get_mnist_loader_from_path
    parameters:
      train_image_file: D:\data\Handwrite-MNIST\MNIST_train-images-idx3-ubyte.gz
      train_label_file: D:\data\Handwrite-MNIST\MNIST_train-labels-idx1-ubyte.gz
      test_image_file: D:\data\Handwrite-MNIST\MNIST_t10k-images-idx3-ubyte.gz
      test_label_file: D:\data\Handwrite-MNIST\MNIST_t10k-labels-idx1-ubyte.gz
      batch_size: *global_batch_size
    implicit_parameters: null


  builder: &builder
    parser_element: ['builder']
    parser_rule:
      define_file_path: module_lib.builder.normal_builder
      run_key: ConvBuilder
    parameters:
      base_config: null


  model: &model
    parser_element: ['model']
    parser_rule:
      define_file_path: module_lib.base_model.classification.lenet
      run_key: create_lenet5
    parameters:
      output_class: 10
    implicit_parameters: null


  loss_function: &loss_function
    parser_element: ['loss_function']
    parser_rule:
      define_file_path: torch.nn
      run_key: CrossEntropyLoss
    parameters: null


  get_model_param: &get_model_param
    parser_element: ['params']
    parser_rule:
      define_file_path: utils.get_model_param
      run_key: _get_model_param
    parameters: 
      weight_decay_list: [*weight_decay]
    implicit_parameters: 
    implicit_parameters_args: ['model']


  optimizer: &optimizer
    parser_element: ['optimizer']
    parser_rule:
      define_file_path:  torch.optim
      run_key: Adam
    parameters: 
      lr: 0.001
      # betas: (0.9,0.999)
      weight_decay: *weight_decay
    implicit_parameters: ['params']

  lr_scheduler: &lr_scheduler
    parser_element: ['lr_scheduler']
    parser_rule:
      define_file_path: torch.optim.lr_scheduler
      run_key: MultiStepLR
    parameters:
      milestones: [20, 40]
      gamma: 0.1
      last_epoch: -1
    implicit_parameters: ['optimizer']

 
  model_script: &model_script
    parser_element: ['model_script']
    parser_rule: 
      define_file_path: luanch_script.model_script.classification_script_mnist
      run_key: classification_script
    parameters: 
      device: *device
    implicit_parameters: ['model','loss_function','train_loader','eval_loader','optimizer', 'lr_scheduler']





